# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "legacy_auto_complete"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sebastian Johnsson"]
  s.date = "2012-01-30"
  s.description = "Rails' auto_complete plugin (for Prototype) as a gem"
  s.email = "sebastian@agiley.se"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
    "README",
    "Rakefile",
    "VERSION",
    "legacy_auto_complete.gemspec",
    "lib/auto_complete.rb",
    "lib/auto_complete/auto_completer.rb",
    "lib/auto_complete/auto_completer_macros_helper.rb",
    "lib/auto_complete/railtie.rb",
    "test/auto_complete_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "https://github.com/Agiley/auto_complete"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Rails' auto_complete plugin (for Prototype) as a gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rails>, ["~> 3.2.1"])
      s.add_development_dependency(%q<test-unit>, ["~> 2.4.5"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.2.1"])
      s.add_dependency(%q<test-unit>, ["~> 2.4.5"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.2.1"])
    s.add_dependency(%q<test-unit>, ["~> 2.4.5"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

